image: debian/stable
packages:
- rsync
- curl
sources:
- https://git.sr.ht/~huehn/www.thomas-huehn.de
secrets:
- d75d3b96-f524-42c2-adc5-43ce6ac7bf2f
- b3dc0e2a-38b9-4e85-8514-2f01ed189aec
tasks:
- get-hugo: |
        curl https://github.com/gohugoio/hugo/releases/download/v0.97.2/hugo_extended_0.97.2_Linux-64bit.deb
        sudo apt install hugo_extended_0.97.2_Linux-64bit.deb --yes
- build: |
    cd www.thomas-huehn.de
    git submodule init
    git submodule update
    /usr/local/bin/hugo --minify
- deploy: |
    cd www.thomas-huehn.de.de
    ln -sf ~/.ssh/b3dc0e2a-38b9-4e85-8514-2f01ed189aec ~/.ssh/id_rsa
    rsync --rsh="ssh -o StrictHostKeyChecking=no" -rzP public/ sourcehut-2uo@94.130.150.135:/www.thomas-huehn.de
